version: '3.3'

services:
  db_vmst:
    image: postgres:13.3
    container_name: db_vmst
    ports:
      - 5432:5432
    networks:
      - local
    environment:
      - POSTGRES_PASSWORD=postgres

networks:
  local:
