name: Pull request pipeline

on:
  pull_request: {}
  workflow_dispatch: {}

jobs:
  check-apps:
    runs-on: ubuntu-20.04
    timeout-minutes: 20
    services:
      postgres:
        image: postgres:13.3
        env:
          POSTGRES_PASSWORD: postgres
          options: >-
            --health-cmd pg_isready
            --health-interval 10s
            --health-timeout 5s
            --health-retries 5
        ports:
          - 5432:5432
    strategy:
      matrix:
        service:
          - vmst
          - islandis

    steps:
      - uses: actions/checkout@v2

      - name: Cache node dependencies
        uses: actions/cache@v2
        with:
          path: apps/${{ matrix.service}}/node_modules
          key: ${{ runner.os }}-yarn-${{ matrix.service }}-${{ hashFiles('apps/${{ matrix.service }}/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-${{ matrix.service }}-

      - name: Install dependencies
        run: yarn install --frozen-lockfile
        working-directory: apps/${{ matrix.service }}

      - name: Run linter
        run: yarn lint
        working-directory: apps/${{ matrix.service }}

      - name: Run formatter
        run: yarn format:check
        working-directory: apps/${{ matrix.service }}

      - name: Run unit tests
        run: yarn test
        working-directory: apps/${{ matrix.service }}

      - name: Run e2e tests
        run: |
          yarn migrate
          yarn test:e2e
        working-directory: apps/${{ matrix.service }}

      - name: Run build
        run: yarn build
        working-directory: apps/${{ matrix.service }}

  check-infra:
    runs-on: ubuntu-20.04
    timeout-minutes: 20

    steps:
      - uses: actions/checkout@v2
      - uses: actions/checkout@v2
        with:
          repository: tfutils/tfenv
          path: .tfenv

      - name: Add tfenv to PATH
        run: echo "PATH=.tfenv/bin:$PATH" >> $GITHUB_ENV

      - name: Install Terraform
        run: tfenv install

      - name: Perform format check
        run: terraform fmt -check -diff -recursive .
        working-directory: infra
